#!/bin/bash

images=()
swaylock_args=()

# Make screenshots of each output
for output in $(swaymsg -t get_outputs | jq -r '.[] .name'); do
    image=$(mktemp --suffix=.png)

    images+=($image)
    swaylock_args+=(-i $output:$image)

    grim -o $output $image
done

# Pixelize each output in parallel
printf '%s\n' "${images[@]}" | xargs -P 0 -I{} convert -scale 5% -scale 2000% {} {}

swaylock ${swaylock_args[@]}
rm ${images[@]}
