#!/bin/bash
set -e

# Dependencies
# ============
#
# * jq
# * zenity

# Static settings
# ===============
initial_search_dir="$HOME/Projekte"

# "Main"
# ======
editor=code
run_editor() {
    $editor "$1"
}

# select the first directory so arrow keys can be used right away
# (assuming there are only subdirectories, no files)
first_project_dir="$initial_search_dir"/$(ls -1 "$initial_search_dir" | sort -n | head -1)
project_dir=$(zenity --file-selection --directory --filename="$first_project_dir")

if [[ "$project_dir" ]]; then
    workspace_number=$(swaymsg -t get_workspaces | jq '.[] | select(.focused == true).num')
    project_dir_basename=$(basename "$project_dir")
    new_workspace_name="$workspace_number:$workspace_number: $project_dir_basename"

    swaymsg "rename workspace to \"$new_workspace_name\""
    run_editor "$project_dir"
fi
