#!/bin/bash

# Get and optionally updates the volume in quodlibet with logarithmic scale
# rather than the default linear scale.
#
# Usage:
#   Print current volume: quodlibet-volume
#   Update and print volume:
#     quodlibet-volume <volume: int>
#     quodlibet-volume +<increment: int>
#     quodlibet-volume -<decrement: int>

set -eo pipefail

cur_vol=$(quodlibet --status | awk '{ printf "%.f", $3 ^ (1/3) * 100 }')
change="$1"

if [[ -n "$change" ]]; then
    if [[ "${change::1}" =~ [+-] ]]; then
        vol=$(($cur_vol $1))
    else
        vol="$1"
    fi
    quodlibet --volume="$(awk '{ print ($1 / 100) ^ 3 * 100 }' <<< $vol)"
else
    vol="$cur_vol"
fi

echo "$vol"
