#!/usr/bin/env sh
zenity --question --title="Ruhezustand" --text="Wollen sie den Computer in den Ruhezustand versetzen?"
response=$?

if [ "$response" = "0" ]; then
	i3lock -c 000000
	systemctl hibernate
fi
exit 0
