#!/usr/bin/env sh
zenity --question --title="Bereitschaftsmodus" --text="Wollen sie den Computer in den Bereitschaftsmodus versetzen?"
response=$?

if [ "$response" = "0" ]; then
    systemctl suspend
fi
exit 0
